/**
 * Builds a branded .docx from a DataLayerDoc.
 *
 * Structure:
 *   Cover page  — project title + date
 *   Overview    — standard intro paragraph
 *   TOC         — auto-generated by Word on open
 *   Sections    — grouped by category (Heading 1) → event (Heading 2)
 *                 trigger · code block · fields table · comments
 */
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  ShadingType,
  TableOfContents,
  PageBreak,
} from 'docx'

// ─── Brand ────────────────────────────────────────────────────────────────────

const BRAND_BLUE  = '2563EB'   // Meliorum/GA4 blue
const HEADING_DARK = '1E293B'  // slate-800
const MONO_BG     = 'F8FAFC'
const CELL_HEADER = 'EFF6FF'
const CELL_BORDER = 'CBD5E1'
const FONT_BODY   = 'Poppins'
const FONT_CODE   = 'Courier New'
const SIZE_NORMAL = 20          // 10pt
const SIZE_SMALL  = 18          // 9pt
const SIZE_H1     = 36          // 18pt
const SIZE_H2     = 28          // 14pt
const SIZE_H3     = 24          // 12pt

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ExportParam {
  name:        string
  description: string
  type:        string
  value:       string   // "dynamic" or constant
  example:     string
  notes:       string
}

export interface ExportEcommerceNote {
  fieldPath: string
  notes:     string
}

export interface ExportSection {
  eventName:      string
  category:       string
  trigger:        string
  codeBlock:      string
  params:         ExportParam[]
  ecommerceNotes: ExportEcommerceNote[]
  comments:       string[]
  isDone:         boolean
  isTested:       boolean
  testResult:     string | null
}

export interface ExportDoc {
  projectName:  string
  clientName:   string
  sections:     ExportSection[]
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const NOBORDER = {
  top:    { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  bottom: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  left:   { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  right:  { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
}

const BORDER = {
  top:    { style: BorderStyle.SINGLE, size: 4, color: CELL_BORDER },
  bottom: { style: BorderStyle.SINGLE, size: 4, color: CELL_BORDER },
  left:   { style: BorderStyle.SINGLE, size: 4, color: CELL_BORDER },
  right:  { style: BorderStyle.SINGLE, size: 4, color: CELL_BORDER },
}

function run(text: string, opts: {
  bold?: boolean; italic?: boolean; color?: string;
  font?: string; size?: number; underline?: boolean
} = {}): TextRun {
  return new TextRun({
    text,
    font:     opts.font  ?? FONT_BODY,
    size:     opts.size  ?? SIZE_NORMAL,
    bold:     opts.bold  ?? false,
    italics:  opts.italic ?? false,
    color:    opts.color,
    underline: opts.underline ? { type: 'single' as const } : undefined,
  })
}

function codeRun(text: string): TextRun {
  return new TextRun({ text, font: FONT_CODE, size: SIZE_SMALL })
}

function para(children: TextRun[], opts: {
  align?: (typeof AlignmentType)[keyof typeof AlignmentType]
  before?: number; after?: number
  shading?: { color: string; fill: string }
} = {}): Paragraph {
  return new Paragraph({
    children,
    alignment: opts.align,
    spacing: { before: opts.before ?? 0, after: opts.after ?? 160 },
    shading: opts.shading
      ? { type: ShadingType.SOLID, color: opts.shading.color, fill: opts.shading.fill }
      : undefined,
  })
}

function heading(text: string, level: string, opts: { before?: number; after?: number } = {}): Paragraph {
  return new Paragraph({
    text,
    heading: level as 'Heading1' | 'Heading2' | 'Heading3' | 'Heading4' | 'Title',
    spacing: { before: opts.before ?? 400, after: opts.after ?? 160 },
  })
}

function headerCell(text: string): TableCell {
  return new TableCell({
    borders: BORDER,
    shading: { type: ShadingType.SOLID, color: CELL_HEADER, fill: CELL_HEADER },
    children: [new Paragraph({
      children: [run(text, { bold: true, size: SIZE_SMALL })],
      spacing: { before: 60, after: 60 },
    })],
  })
}

function dataCell(text: string, mono = false): TableCell {
  return new TableCell({
    borders: BORDER,
    children: [new Paragraph({
      children: [mono ? codeRun(text) : run(text, { size: SIZE_SMALL })],
      spacing: { before: 60, after: 60 },
    })],
  })
}

// ─── Main builder ─────────────────────────────────────────────────────────────

export async function buildDocx(data: ExportDoc): Promise<ArrayBuffer> {
  const { projectName, clientName, sections } = data
  const today = new Date().toLocaleDateString('en-AU', {
    day: 'numeric', month: 'long', year: 'numeric',
  })

  const body: (Paragraph | Table | TableOfContents)[] = []

  // ── Cover page ──────────────────────────────────────────────────────────────
  body.push(
    para([run('')], { before: 800, after: 0 }),  // top padding

    // Logo placeholder — replace with actual image once provided
    para(
      [run('[LOGO]', { bold: true, color: BRAND_BLUE, size: 28 })],
      { align: AlignmentType.CENTER, after: 600 }
    ),

    para(
      [run('DataLayer Implementation Guide', { bold: true, size: 40, color: BRAND_BLUE })],
      { align: AlignmentType.CENTER, after: 200 }
    ),

    para(
      [run(clientName || projectName, { bold: true, size: SIZE_H2, color: HEADING_DARK })],
      { align: AlignmentType.CENTER, after: 100 }
    ),

    para(
      [run(projectName !== clientName ? projectName : '', { size: SIZE_NORMAL, color: '64748B' })],
      { align: AlignmentType.CENTER, after: 400 }
    ),

    para(
      [run(today, { size: SIZE_SMALL, color: '94A3B8' })],
      { align: AlignmentType.CENTER, after: 0 }
    ),

    // Page break after cover
    new Paragraph({ children: [new PageBreak()], spacing: { after: 0 } }),
  )

  // ── Overview ─────────────────────────────────────────────────────────────────
  body.push(
    heading('Overview', HeadingLevel.HEADING_1, { before: 0, after: 200 }),

    para([
      run(
        `The following document outlines the code requirements for the ${clientName || projectName} website. ` +
        `It is in line with Google's best practices outlined here: ` +
        `https://developers.google.com/tag-manager/devguide`,
      ),
    ], { after: 200 }),

    para([
      run(
        `If any request is a large effort or you have any questions, don't hesitate to contact me at sarah@meliorum.com.au`,
      ),
    ], { after: 400 }),

    // Page break before TOC
    new Paragraph({ children: [new PageBreak()], spacing: { after: 0 } }),
  )

  // ── Table of Contents ────────────────────────────────────────────────────────
  body.push(
    heading('Contents', HeadingLevel.HEADING_1, { before: 0, after: 240 }),
    new TableOfContents('Contents', {
      hyperlink:        true,
      headingStyleRange: '1-3',
    }),
    new Paragraph({ children: [new PageBreak()], spacing: { after: 0 } }),
  )

  // ── Sections grouped by category ─────────────────────────────────────────────
  // Group sections by category
  const grouped = new Map<string, ExportSection[]>()
  for (const s of sections) {
    const cat = s.category || '(uncategorised)'
    if (!grouped.has(cat)) grouped.set(cat, [])
    grouped.get(cat)!.push(s)
  }

  for (const [category, catSections] of grouped) {
    // Category heading (Heading 1 — appears in TOC)
    body.push(
      heading(
        category.charAt(0).toUpperCase() + category.slice(1),
        HeadingLevel.HEADING_1,
        { before: 200, after: 200 }
      )
    )

    for (const section of catSections) {
      const fullEventName = section.category
        ? `custom.${section.category}.${section.eventName}`
        : section.eventName

      // Event heading (Heading 2 — appears in TOC)
      body.push(heading(fullEventName, HeadingLevel.HEADING_2, { before: 400, after: 160 }))

      // Status
      const statusParts: TextRun[] = []
      if (section.isDone)   statusParts.push(run('✓ Done   ', { color: '166534', size: SIZE_SMALL }))
      if (section.isTested) statusParts.push(run('✓ Tested   ', { color: '1d4ed8', size: SIZE_SMALL }))
      if (section.testResult) {
        const passed = section.testResult === 'passed'
        statusParts.push(run(passed ? '✓ Passed' : '✗ Failed', {
          color: passed ? '166534' : 'b91c1c', size: SIZE_SMALL,
        }))
      }
      if (statusParts.length > 0) {
        body.push(para(statusParts, { after: 120 }))
      }

      // Trigger
      if (section.trigger) {
        body.push(para([
          run('Trigger: ', { bold: true }),
          run(section.trigger),
        ], { after: 200 }))
      }

      // Code block
      if (section.codeBlock) {
        body.push(para([run('dataLayer.push:', { bold: true })], { after: 60 }))
        for (const line of section.codeBlock.split('\n')) {
          body.push(new Paragraph({
            children: [codeRun(line || ' ')],
            spacing: { before: 0, after: 0 },
            shading: { type: ShadingType.SOLID, color: MONO_BG, fill: MONO_BG },
          }))
        }
        body.push(para([run('')], { after: 200 }))
      }

      // Fields table (params)
      if (section.params.length > 0) {
        body.push(para([run('Fields explained:', { bold: true })], { after: 80 }))

        const headerRow = new TableRow({ children: [
          headerCell('Name'),
          headerCell('Description'),
          headerCell('Type'),
          headerCell('Value'),
          headerCell('Example'),
          headerCell('Notes'),
        ]})

        const dataRows = section.params.map((p) => new TableRow({ children: [
          dataCell(p.name, true),
          dataCell(p.description),
          dataCell(p.type, true),
          dataCell(p.value === 'dynamic' ? '(dynamic)' : p.value),
          dataCell(p.example, true),
          dataCell(p.notes),
        ]}))

        body.push(new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [headerRow, ...dataRows],
        }))
        body.push(para([run('')], { after: 200 }))
      }

      // Ecommerce notes
      if (section.ecommerceNotes.length > 0) {
        const noted = section.ecommerceNotes.filter((n) => n.notes)
        if (noted.length > 0) {
          body.push(para([run('Ecommerce fields:', { bold: true })], { after: 80 }))

          const headerRow = new TableRow({ children: [
            headerCell('Field'),
            headerCell('Notes'),
          ]})

          const dataRows = noted.map((n) => new TableRow({ children: [
            dataCell(n.fieldPath, true),
            dataCell(n.notes),
          ]}))

          body.push(new Table({
            width: { size: 60, type: WidthType.PERCENTAGE },
            rows: [headerRow, ...dataRows],
          }))
          body.push(para([run('')], { after: 200 }))
        }
      }

      // Comments
      if (section.comments.length > 0) {
        body.push(para([run('Comments:', { bold: true })], { after: 60 }))
        for (const comment of section.comments) {
          body.push(para([run(`• ${comment}`, { italic: true })], { after: 60 }))
        }
        body.push(para([run('')], { after: 200 }))
      }
    }
  }

  // ── Document ────────────────────────────────────────────────────────────────
  const doc = new Document({
    sections: [{ children: body }],
    styles: {
      default: {
        document: {
          run: { font: FONT_BODY, size: SIZE_NORMAL, color: HEADING_DARK },
        },
      },
      paragraphStyles: [
        {
          id:       'Heading1',
          name:     'Heading 1',
          basedOn:  'Normal',
          next:     'Normal',
          run:      { font: FONT_BODY, size: SIZE_H1, bold: true, color: BRAND_BLUE },
          paragraph: { spacing: { before: 400, after: 160 } },
        },
        {
          id:       'Heading2',
          name:     'Heading 2',
          basedOn:  'Normal',
          next:     'Normal',
          run:      { font: FONT_BODY, size: SIZE_H2, bold: true, color: HEADING_DARK },
          paragraph: { spacing: { before: 320, after: 120 } },
        },
        {
          id:       'Heading3',
          name:     'Heading 3',
          basedOn:  'Normal',
          next:     'Normal',
          run:      { font: FONT_BODY, size: SIZE_H3, bold: true, color: HEADING_DARK },
          paragraph: { spacing: { before: 240, after: 80 } },
        },
      ],
    },
  })

  const buf = await Packer.toBuffer(doc)
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer
}
